# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "trading.log"

# Paths Configuration
paths:
  base_dir: "./backtesting"
  data_dir: "./backtesting/data"
  model_dir: "./backtesting/models"
  results_dir: "./backtesting/results"
  log_dir: "./backtesting/logs"
  db_path: "data/db/market_data.db"
  cache_dir: "data/cache"
  metadata_dir: "data/cache/metadata"
  daily_data_dir: "data/cache/daily_data"
  temp_dir: "data/cache/temp/downloads"

# Cache Configuration
cache:
  max_memory_cache_size: 1000
  cache_expiry_days: 1
  update_frequency: "1d"
  compression_type: "parquet"

# Download Configuration
download:
  max_retries: 3
  retry_delay: 5
  batch_size: 100
  timeout: 30

# Validation Configuration
validation:
  min_data_points: 50
  max_missing_pct: 0.1
  price_threshold: 5.00

# Factor Pipeline Configuration
factor_pipeline:
  model_weight: 0.5
  mean_reversion_weight: 0.5
  min_score_threshold: 0.1

# Portfolio Strategy Configuration
portfolio_strategy:
  max_position_size: 0.10

# Model Configuration
model:
  # Model Versioning and Type
  version: "v2.0"
  type: "ImprovedLSTM"
  input_size: 49  # Matches the input size from model configuration
  
  # LSTM Architecture - Updated to match best parameters and actual model
  sequence_length: 20      # From best parameters
  hidden_size: 256        # From best parameters
  num_layers: 2          # From best parameters
  bidirectional: true    # From model configuration
  attention_heads: 4     # From model configuration (128/32 = 4 heads)
  use_layer_norm: true   # From model configuration
  residual_connections: true
  
  # Training Parameters - Updated to match best parameters
  batch_size: 32        # From best parameters
  num_epochs: 100
  learning_rate: 0.001   # From best parameters
  train_test_split: 0.8
  
  # Early Stopping
  early_stopping_patience: 10
  min_delta: 0.001
  
  # Regularization - Updated to match best parameters
  dropout: 0.1           # From best parameters
  weight_decay: 0.001     # From best parameters

  # Validation Parameters
  validation:
    temporal_checks:
      enabled: true
      max_window_size: 21
    feature_checks:
      enabled: true
      correlation_threshold: 0.9
      suspicious_window: 20
    direction_accuracy_threshold: 0.55  # Minimum directional accuracy
    sharpe_ratio_threshold: 1.0        # Minimum Sharpe ratio
    ic_threshold: 0.05                 # Minimum information coefficient
  
  # Learning Rate Scheduler
  lr_scheduler:
    type: "onecycle"
    max_lr: 0.01
    pct_start: 0.3
    anneal_strategy: "cos"

# Feature Engineering Configuration
features:
  # Technical Indicators
  technical:
    moving_averages:
      - type: "SMA"
        periods: [5, 10, 20, 50, 200]
      - type: "EMA"
        periods: [12, 26]
    
    momentum:
      rsi:
        period: 14
      macd:
        fast_period: 12
        slow_period: 26
        signal_period: 9
      stochastic:
        k_period: 14
        d_period: 3
    
    volatility:
      bollinger_bands:
        period: 20
        std_dev: 2
      atr:
        period: 14
    
    volume:
      obv: true
      volume_ma:
        periods: [10, 20]

  # Price Features
  price:
    returns:
      periods: [1, 5, 10, 20]
    log_returns: true
    rolling_stats:
      windows: [5, 10, 20]
      metrics: ["mean", "std", "skew"]

  # Sequence Features
  sequence:
    lookback_window: 10
    target_lookahead: 5
    
  # Feature Preprocessing
  preprocessing:
    scaling:
      method: "standard"  # or "minmax", "robust"
    outlier_threshold: 3.0
    fill_method: "ffill"
    minimum_periods: 20

# Mean Reversion Configuration
mean_reversion:
  lookback: 20
  z_score_threshold: 1.5

# Hyperparameter Search Configuration
hyperparameter_search:
  # LSTM Architecture Search Space - Adjusted to include best found values
  hidden_size: [128, 256, 512]  # 256 was best
  num_layers: [1, 2, 3]         # 2 was best
  dropout: [0.1, 0.2, 0.3]      # 0.2 was best
  attention_heads: [2, 4, 8]     
  
  # Architecture Options
  bidirectional: [true, false]
  use_layer_norm: [true]        # Layer norm was successful
  residual_connections: [true]   # Residual connections were successful
  
  # Sequence Parameters
  sequence_length: [5, 10, 20]   # 10 was best
  
  # Training Parameters
  batch_size: [32, 64, 128]     # 128 was best
  learning_rate: [0.0001, 0.001, 0.01]  # 0.001 was best
  weight_decay: [0.001, 0.01, 0.1]      # 0.01 was best
  
  # Lookback Buffer
  lookback_buffer: 10
  
  # Search Configuration
  optimization_tool: "optuna"  # Tool for optimization
  max_trials: 50              # Number of trials
  direction: "minimize"        # Optimization direction


# TESTING CONFIGURATION
model_params:
  sequence_length: 20
  prediction_horizon: 5
  movement_threshold: 0.005
  hidden_size: 128
  num_layers: 2
  dropout: 0.2
  
training_params:
  batch_size: 32
  learning_rate: 0.001
  max_grad_norm: 1.0
  validation_ratio: 0.2
  
prediction_params:
  confidence_threshold: 0.6
  volatility_threshold: 0.25
  regime_factors:
    trending_up: 1.1
    trending_down: 1.1
    ranging: 0.9
    high_volatility: 0.8