# Existing logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "trading.log"

# Existing paths configuration
paths:
  base_dir: "./backtesting"
  data_dir: "./backtesting/data"
  model_dir: "./backtesting/models"
  results_dir: "./backtesting/results"
  log_dir: "./backtesting/logs"
  db_path: 'data/db/market_data.db'
  cache_dir: 'data/cache'
  metadata_dir: 'data/cache/metadata'
  daily_data_dir: 'data/cache/daily_data'
  temp_dir: 'data/cache/temp/downloads'

# Existing cache configuration
cache:
  max_memory_cache_size: 1000
  cache_expiry_days: 1
  update_frequency: '1d'
  compression_type: 'parquet'

# Existing download configuration
download:
  max_retries: 3
  retry_delay: 5
  batch_size: 100
  timeout: 30

# Existing validation configuration
validation:
  min_data_points: 50
  max_missing_pct: 0.1
  price_threshold: 5.00

# Existing factor pipeline configuration
factor_pipeline:
  model_weight: 0.5
  mean_reversion_weight: 0.5
  min_score_threshold: 0.1

# Existing portfolio strategy configuration
portfolio_strategy:
  max_position_size: 0.10

# Updated and New Model Configuration
model:
  # Model versioning and type
  version: "v1.0"
  type: "LSTM"
  input_size: 20  # Number of features after feature engineering
  
  # LSTM Architecture
  sequence_length: 10
  hidden_size: 64
  num_layers: 2
  
  # Training Parameters
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.001
  train_test_split: 0.8
  
  # Early Stopping
  early_stopping_patience: 10
  min_delta: 0.001
  
  # Regularization
  dropout: 0.2
  weight_decay: 0.0001

  validation:
    direction_accuracy_threshold: 0.55  # Minimum directional accuracy
    sharpe_ratio_threshold: 1.0        # Minimum Sharpe ratio
    ic_threshold: 0.05                 # Minimum information coefficient
  
  # Training parameters
  lr_scheduler:
    factor: 0.5
    patience: 5
    min_lr: 0.00001

# Feature Engineering Configuration
features:
  # Technical Indicators
  technical:
    moving_averages:
      - type: "SMA"
        periods: [5, 10, 20, 50, 200]
      - type: "EMA"
        periods: [12, 26]
    
    momentum:
      rsi:
        period: 14
      macd:
        fast_period: 12
        slow_period: 26
        signal_period: 9
      stochastic:
        k_period: 14
        d_period: 3
    
    volatility:
      bollinger_bands:
        period: 20
        std_dev: 2
      atr:
        period: 14
    
    volume:
      obv: true
      volume_ma:
        periods: [10, 20]

  # Price Features
  price:
    returns:
      periods: [1, 5, 10, 20]
    log_returns: true
    rolling_stats:
      windows: [5, 10, 20]
      metrics: ["mean", "std", "skew"]

  # Sequence Features
  sequence:
    lookback_window: 10
    target_lookahead: 5
    
  # Feature Preprocessing
  preprocessing:
    scaling:
      method: "standard"  # or "minmax", "robust"
    outlier_threshold: 3.0
    fill_method: "ffill"
    minimum_periods: 20

# Mean Reversion Configuration (existing)
mean_reversion:
  lookback: 20
  z_score_threshold: 1.5