# config.yaml
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "trading.log"

paths:
  base_dir: "./backtesting"
  data_dir: "./backtesting/data"
  model_dir: "./backtesting/models"
  results_dir: "./backtesting/results"
  log_dir: "./backtesting/logs"
  db_path: 'data/db/market_data.db'
  cache_dir: 'data/cache'
  metadata_dir: 'data/cache/metadata'
  daily_data_dir: 'data/cache/daily_data'
  temp_dir: 'data/cache/temp/downloads'

# BacktestDataManager Configuration
cache:
  max_memory_cache_size: 1000  # Maximum number of symbols to keep in memory
  cache_expiry_days: 1         # Number of days before cache expires
  update_frequency: '1d'       # Update frequency for cache
  compression_type: 'parquet'  # Type of compression for stored data

download:
  max_retries: 3              # Maximum number of download attempts
  retry_delay: 5              # Delay between retries in seconds
  batch_size: 100            # Number of parallel downloads
  timeout: 30                # Download timeout in seconds

# Factor Pipeline Configuration
validation: # Also used in the BacktestDataManager
  min_data_points: 50        # Minimum required data points for a valid symbol
  max_missing_pct: 0.1       # Maximum allowed percentage of missing values
  price_threshold: 5.00      # Used in basic_screen() method

factor_pipeline:
  model_weight: 0.5         # Used in analyze_stocks() method
  mean_reversion_weight: 0.5 # Used in analyze_stocks() method
  min_score_threshold: 0.1  # Used in rank_opportunities() method

portfolio_strategy:
  max_position_size: 0.10   # Used in rank_opportunities() method


# Model Configuration
model_pipeline:
  model_name: 'RandomForestClassifier'
  model_params:
    n_estimators: 100
    max_depth: 5
    random_state: 42

# Mean Revision Configuration
mean_reversion:
  lookback: 20
  z_score_threshold: 1.5